services:
  bmw-bridge:
    # WICHTIG: Hier steht jetzt der neue, kurze Name!
    image: ghcr.io/bausi2k/bmw-mqtt-bridge:latest
    
    container_name: bmw-bridge
    restart: unless-stopped
    
    ports:
      - "${WEB_PORT:-8999}:${WEB_PORT:-8999}"
    
    env_file:
      - .env
    
    volumes:
      - ./bmw_tokens.json:/app/bmw_tokens.json
      - ./vehicle.json:/app/vehicle.json
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./data:/app/data
      
    environment:
      - TZ=Europe/Vienna